server:
  port: 8092
  servlet:
    context-path: /springcloudconfig

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nanshanGuo/SpringCloudDemo
          search-paths: spring-cloud-config-repo
          username: ""
          password: ""
      label: master
  rabbitmq:
    host: 192.168.10.104
    port: 5672
    username: admin
    password: admin


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:8090/springcloudeureka/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: send-8092.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址